- README.md
- lib/formatter.js
- lib/html-to-text.js
1. I've added support for pre - as that is already raw text it shouldn't be formatted anymore.
2. Additionally there are two options for a-tags (described in the README).
3. I've also had problems with the hr - for some reason in some cases a new line was missing, so I've added one manually. For me it's better there is a new line too much than one missing.
> Add support for pre-tags, add options for links

- test/test.html
- test/test.txt
I'm pretty sure that the HTML ``the <a href="http://example.com">test</a>!`` should render in plaintext as ``the test [http://example.com/]!`, not ``the test [http://example.com/] !``, which is how it does now. (Note the space before the exclamation point). So I wanted to add a test for this case, to document it as an issue and make it easy to track when it's fixed.
> Add failing test case for links followed by punctuation

- package.json
iojs have already released 2.2.1 version, so node-html-to-text need to update engine field.
btw, do you really need this field? cause it’s not only complaining and not really care about engine versions, as far as library is not testing under all stated engines in the CI
> bump iojs up to @2.x

- package.json
What do you think @mlegenhausen? A [few](https://github.com/elastic/elasticsearch-js/commit/6e0d273d75201306a493de8471f9814625f5dc4c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L101) others have done this.
> Updated engines to remove upper version constraint

- lib/html-to-text.js
When using Browserify to pack `html-to-text` for use on the client-side, Internet Explorer throws the dreaded `Expected Identifier` error message. There are two items fixed here that corrects that error, allowing `html-to-text` to be used on the client-side when bundled with Browserify.
First, the extraneous comma in the declaration for the `options` object. Second, Internet Explorer really *really* doesn't like using `class` as an identifier, so to access a property named `class`, you should use the named index (square bracket) syntax, which was corrected in the `containsTable` function.
Hope this helps some others!
> Removed an extra comma & updated attr accessor for 'class' for IE fix

- lib/helper.js
- test/html-to-text.js
Instead of matching *any* character, match any non-& character. This should fix issue #69, where the string being processed included more than one & character.
> make entity regex less greedy (issue #69)

- README.md
- lib/formatter.js
- lib/helper.js
- lib/html-to-text.js
- test/html-to-text.js
This will not change anything for current users, but exposes a new option: preserveNewlines, which causes newlines in text to be retained by the output.
> Preserve newlines in text

- README.md
> Fixed html-to-html error in readme

- lib/formatter.js
<div>Hallo
<ul>
<li>1</li>
<li>2</li>
</ul>
</div>
Current output:
Hallo * 1
* 2
Correct output:
Hallo
* 1
* 2
> start lists with a new line

- lib/formatter.js
- test/html-to-text.js
Currently, HTML entities are not parsed inside the `alt` tag of images.
> bugfix: correctly handle HTML entities for images

- README.md
- lib/formatter.js
- lib/html-to-text.js
This exposes and option to not uppercase headers (in our case, it was capitalizing django vars which was causing issues). Default set to true.
> Expose option to not uppercase headers

- test/html-to-text.js
New tests to show that long words are left alone unless 'longWordSplit' is configured
> Long word tests

- lib/formatter.js
- lib/helper.js
- lib/html-to-text.js
- test/html-to-text.js
- test/test.html
- test/test.txt
`foo<strong>bar</strong>` will now be converted to `foobar` (no extra whitespace).
Previously, any block of text or `<a>` tag would introduce leading whitespace (unless already parsed text ends with one). With these changes, extra leading whitespace is never added. Instead, trailing whitespace is preserved, and leading whitespace is removed if it would result in double whitespace.
One anomaly I found is that text followed by a paragraph would result in nothing between the two. I didn't fix this deliberately, but as a side-effect of the fix for the issue described above, an extra whitespace is now added to the end of the first line, e.g.
`foo<p>bar</p>` results in `foo bar` (it used to render as `foobar`).
I don't think this new behaviour is incorrect, but most likely the proper fix would …
> Prevent extra whitespace from being added (fix #88)

- lib/formatter.js
- lib/html-to-text.js
- test/html-to-text.js
In #99 I've introduced a bug where `foo<span> </span>bar` would be formatted without any whitespace (`foobar` instead of `foo bar`). Parser was set up to ignore all whitespace-only html nodes; however, as previously a space was always added before any node, this wasn't an issue.
I've changed parser settings not to ignore any nodes. As both list formatters started generating a new item for whitespace nodes, I had to filter those out. I've also added tests to make sure that empty lists (`<ul></ul>` `<ol></ol>`) are handled correctly.
> Do not ignore whitespace nodes

- lib/formatter.js
- test/html-to-text.js
When colspan is not a numeric value, filling of empty columns will fail when attempting to calculate how many columns need to be filled.
We noticed this after recieving email with 
``` html
<table>
<tr>
<td colspan="100%">Some arbitrary text</td>
</tr>
<tr>
<td colspan="100%" style="font-size: 14px">Some more arbitrary text</td>
</tr>
</table>
```
Which when attempting to parse them results in
```
RangeError: Invalid array length
```
> Treat non-numeric colspans as zero and handle them gracefully

- README.md
- lib/formatter.js
- lib/html-to-text.js
- test/html-to-text.js
Currently paragraphs are converted with a single line, ie.
```
<p>First paragraph</p><p>Second paragraph</p>
```
becomes
```
First paragraph
Second paragraph
```
With the option I have added it is possible to get
```
First paragraph
Second paragraph
```
I have the need to do this because sometimes emails I receive and want to convert have paragraphs `<p>`instead of line breaks `<br>` in them. Most email clients show them with a single line break instead of two and thus I want to do the same.
> Option to format paragraph with single new line

- lib/formatter.js
- test/html-to-text.js
Supporting `type="a"` and `type="A"` as per:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol
> add basic support for alpha ordered list types

- README.md
- lib/html-to-text.js
- test/html-to-text.js
Hey, thanks for that lib, very useful.
Anyway, for some reasons, one can need to use a different formatting than the defaults provided. For example, displaying headings like that:
```
=======
HEADING
=======
```
So this PR simply allow to override keys of the format object with functions of the same signature.
> Ability to pass custom formatting via the `format` option

- lib/formatter.js
- lib/html-to-text.js
- test/html-to-text.js
* Cleanup semicolon style
* Fix indentation on OL LIs
Stubbed out i and I so that they don't throw an exception when encountered, making them fallback to `type="1"`
* added `noAnchorUrl` option to prevent rendering of anchor links (e.g. in-document ToC)
> Implement ol type="i" and "I" as fallbacks to "1", add option to not render anchor links.

- lib/formatter.js
- lib/html-to-text.js
- test/html-to-text.js
Allow for users to specify a different list item prefix other than ` * `
> Option to supply custom unordered list item prefix

- .eslintrc.yml
- example/html-to-text.js
- lib/formatter.js
- lib/html-to-text.js
- test/html-to-text.js
Fixes inadvertent href muting introduced by #123 
I took the liberty of configuring the eslint semi behavior based on the prevailing convention in this code base.
> html entities in hrefs should not trigger noAnchorUrl

- bin/cli.js
- package-lock.json
- package.json
Remove hardcoded CLI options to allow for usage of all settings from documentation.
Replaced 'optimist' library with better supported and smaller library 'minimist'
Added 'ignore-href' and 'ignore-image' aliases to support the previous version's hardcoded option names.
Thanks
> Remove hard-coded CLI options

- lib/helper.js
- test/html-to-text.js
Additional whitespace was appearing after `sup`, `strong`, `b` and similar elements if `preserveNewLines`-option was `true`. See #125 for further details.
Testcase included.
Would you care to publish a new version in npm if this and #161 are good to go?
> Remove additional whitespace after <sup>, fixes #125

- lib/formatter.js
- test/html-to-text.js
As per #47, first element of sublist is now indented.
```
<ul>
<li>1
<ul>
<li>2
<ul>
<li>3.1</li>
<li>3.2</li>
</ul>
</li>
</ul>
</li>
</ul>
```
Correctly outputs as:
```
* 1
* 2
* 3.1
* 3.2
```
Rather than previously outputting as:
```
* 1 * 2 * 3.1
* 3.2
```
Tests updated and passing
> fix(NestedLists): First element of sublist now indented + tests

- lib/formatter.js
- test/html-to-text.js
Sample Text:
```
<blockquote>a<br/>b</blockquote>
```
Current Output:
```
> a
b
```
Expected Output:
```
> a
> b
> Support multiline blockquote

- lib/helper.js
- test/html-to-text.js
It drops leading/trailing Unicode white-spaces (like non-breakable space) if they're not HTML-encoded. 
It is fixed by testing for space by "\s" regexp excluding new line and tab characters.
> fix eaten unicode whitespaces issue

- lib/html-to-text.js
We're using `node-html-to-text` at scale in production for Crisp (https://crisp.chat/); thanks for the work!
Our inbound email system has been put offline a few days ago due to `node-html-to-text` being vulnerable to attacks where the parsed HTML would be either super-deep, or have a LOT of DOM elements, or both.
We noticed via a NodeJS `--prof` check that the `walk()` method was being called a huge number of times. This can be considered as a DOS vulnerability, and was fixed in our fork with hard-coded limits (that are high).
After deploying the patch in this PR in production, we've not seen any more load / downtime issues.
**Here's how we fixed it:**
1. Limit the number of base DOM elements that can be iterated upon (`MAX_BASE` set to 10);
2. Limit the width of a DOM children iteration …
> [DOS vulnerability fix] Limit how many DOM nodes get iterated upon

- packages/html-to-text/README.md
The link to generic formatters in `Override formatting` was incorrect.
> Fix 404 in README.md
